import React from 'react';
import classNames from 'classnames';
import { SectionSplitProps } from '../../utils/SectionProps';
import SectionHeader from './partials/SectionHeader';
import Image from '../elements/Image';

const propTypes = {
  ...SectionSplitProps.types
}

const defaultProps = {
  ...SectionSplitProps.defaults
}

const FeaturesAbout = ({
  className,
  topOuterDivider,
  bottomOuterDivider,
  topDivider,
  bottomDivider,
  hasBgColor,
  invertColor,
  invertMobile,
  invertDesktop,
  alignTop,
  imageFill,
  ...props
}) => {

  const outerClasses = classNames(
    'features-split section',
    topOuterDivider && 'has-top-divider',
    bottomOuterDivider && 'has-bottom-divider',
    hasBgColor && 'has-bg-color',
    invertColor && 'invert-color',
    className
  );

  const innerClasses = classNames(
    'features-split-inner section-inner',
    topDivider && 'has-top-divider',
    bottomDivider && 'has-bottom-divider'
  );

  const splitClasses = classNames(
    'split-wrap',
    invertMobile && 'invert-mobile',
    invertDesktop && 'invert-desktop',
    alignTop && 'align-top'
  );

  const sectionHeader = {
    title: 'Our Purpose',
    paragraph: "Learn about what drove Musaic's creators to develop this novel product."
  };

  const teamHeader = {
      title: "The Musaic Team"
  };

  return (
    <section
      {...props}
      className={outerClasses}
    >
      <div className="container">
        <div className={innerClasses}>
          <SectionHeader data={sectionHeader} className="center-content" />
          <div className={splitClasses}>

            <div className="split-item">
              <div className="split-item-content center-content-mobile reveal-from-left">
                <h3 className="mt-0 mb-12 text-color-primary">
                  Why Musaic?
                  </h3>
                <p className="m-0">
                Musaic was born out of a passion for music, an appreciation for art, and a desire to combine those two fields into a deliverable product. Most modern music-listeners have a playlist, or multiple playlists, that they gravitate towards for any given mood. Musaic aims to capture that same emotional response that drives someone to listen, to drive them to create. <br/><br/>
                Visual art has an uncanny ability to convey emotion, and by using Musaic, that emotion can be translated from sound into sight.
Our application makes it easy to transform music preferences into collage art. Our “Musification” process can turn any photo into a beautiful display of album covers. The images generated by Musaic are easily accessible for users, making it simple to make large scale prints of your Musaic.

                  </p>
              </div>
              <div className={
                classNames(
                  'split-item-image center-content-mobile reveal-from-bottom',
                  imageFill && 'split-item-image-fill'
                )}
                data-reveal-container=".split-item">
                <Image
                  src={require('./../../assets/images/rock_musaic.png')}
                  alt="Features split 01"
                  width={528}
                  height={396} />
              </div>
            </div>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <h3 className="center-content text-color-primary mt-0 mb-12">
            <p> </p>
            <p> </p>
            Meet the Team
            </h3>
            

            <div className="split-item">
                <div className="split-item-content center-content-mobile">
                    <div className="center-content mt-0 mb-12">
                        Claudia "Can't Handle a Surprise" Kuczun
                        <Image
                        src={require('./../../assets/images/claud.jpeg')}
                        alt="About Team Image"
                        style={{width: "350px", height: "350px"}}/>
                    </div>
                </div>
                <div className="split-item-content center-content-mobile">
                    <div className="center-content mt-0 mb-12">
                        Dan Krill
                        <Image
                        src={require('./../../assets/images/dan.jpeg')}
                        alt="About Team Image"
                        style={{width: "350px", height: "350px"}}/>
                    </div>
                </div>
            </div>

            <div className="split-item">
                <div className="split-item-content center-content-mobile">
                    <div className="center-content mt-0 mb-12">
                        Sam Webster
                        <Image
                        src={require('./../../assets/images/sam.jpeg')}
                        alt="About Team Image"
                        style={{width: "350px", height: "350px"}}/>
                    </div>
                </div>
                <div className="split-item-content center-content-mobile">
                    <div className="center-content mt-0 mb-12">
                        Will Halbert
                        <Image
                        src={require('./../../assets/images/will.JPEG')}
                        alt="About Team Image"
                        style={{width: "350px", height: "350px"}}/>
                    </div>
                </div>
            </div>
            <div className="center-content">
            <h3 className="center-content mt-0 mb-12">
            <p> </p>
            <p> </p>
                <i>Memo from the Creators</i>
            </h3>
              <iframe width="560" height="315" src="https://www.youtube.com/embed/kiHv5dSGLnM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
      </div>
      <Image 
            src={require('../../assets/images/musaicbanner.png')}
            alt="Musaic Banner"
            width= {1500}
            height={350}
            className="center-content"
          />
    </section>
  );
}

FeaturesAbout.propTypes = propTypes;
FeaturesAbout.defaultProps = defaultProps;

export default FeaturesAbout;